export const PROJECTS = [
  // Tab 0: AI & Full Stack Projects
  [
    {
      title: "GPT-Style LLM From Scratch",
      desc: "Designed and trained a transformer-based language model from scratch using PyTorch. Implemented custom tokenization pipelines, multi-stage instruction fine-tuning, and training loops with mixed-precision (AMP). This project demonstrates deep understanding of transformer architecture, self-attention mechanisms, and model optimization techniques for production-grade LLM implementation.",
      img: "/images/hero/lexinsight.jpg",
      alt: "GPT-Style LLM From Scratch - Transformer architecture implementation",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: [
        "PyTorch",
        "Transformers",
        "Custom Tokenization",
        "Mixed-Precision Training (AMP)",
        "Python",
      ],
      category: "AI/ML - LLM Development",
      members: ["Tharuneswar Doddi"],
      features: [
        "Custom tokenization pipeline with word-piece tokenization",
        "Multi-stage instruction fine-tuning process",
        "Mixed-precision training with automatic gradient scaling",
        "Checkpoint saving and loading mechanisms",
        "Dataset preparation and training optimization",
        "Transformer architecture implementation from scratch",
      ],
      achievements: [
        "🤖 Complete transformer architecture implementation",
        "📚 Custom tokenizer with vocabulary management",
        "⚡ Mixed-precision training for reduced memory footprint",
        "💾 Production-ready checkpoint management",
      ],
      duration: "2 months",
      status: "Completed",
    },
    {
      title: "AI Interview Evaluation System",
      desc: "Developed an AI-powered interview evaluation platform that automatically scores candidate responses, generates structured performance reports, and provides question-level analytical feedback. Uses advanced scoring algorithms and backend evaluation logic for scalable processing of interview data.",
      img: "/images/hero/pacebeats.jpg",
      alt: "AI Interview Evaluation System - Intelligent scoring platform",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: [
        "FastAPI",
        "Python",
        "MongoDB",
        "Machine Learning",
        "JSON Schema",
      ],
      category: "AI/ML - Evaluation Platforms",
      members: ["Tharuneswar Doddi"],
      features: [
        "Automatic scoring of candidate responses",
        "Structured JSON-based performance reports",
        "Question-level analytical feedback generation",
        "Backend evaluation logic for scalable processing",
        "Interview data storage and retrieval",
      ],
      achievements: [
        "🎯 Intelligent scoring algorithm implementation",
        "📊 Structured reporting system with analytics",
        "⚙️ Scalable backend evaluation architecture",
        "📈 Real-time performance analysis",
      ],
      duration: "1.5 months",
      status: "Completed",
    },
    {
      title: "Face Recognition & Clustering Platform (CampusVibe)",
      desc: "Built a scalable face recognition system using FastAPI, MongoDB, Qdrant, DeepFace, and Docker. Features include bulk image uploads (ZIP + individual), face embedding generation, vector storage, face clustering with similarity search, metadata management, real-time image serving, and optimized handling of high-concurrency requests. Demonstrates production-grade AI system integration and containerized deployment.",
      img: "/images/hero/ars.jpg",
      alt: "CampusVibe - Face Recognition & Clustering Platform",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: [
        "FastAPI",
        "MongoDB",
        "Qdrant",
        "DeepFace",
        "Docker",
        "Python",
      ],
      category: "Full Stack AI - Computer Vision",
      members: ["Tharuneswar Doddi"],
      features: [
        "Bulk image upload (ZIP + individual files)",
        "Face embedding generation with DeepFace",
        "Vector storage in Qdrant",
        "Clustering similar faces with similarity search",
        "Metadata storage in MongoDB",
        "Real-time image serving",
        "High-concurrency request handling",
        "Linux permission optimization for deployment",
      ],
      achievements: [
        "🔍 Scalable vector database architecture",
        "📸 Embedding pipeline for face recognition",
        "🐘 Production Docker containerization",
        "⚡ High-performance concurrent request handling",
      ],
      duration: "2 months",
      status: "Completed",
    },
    {
      title: "Structured OCR Invoice Extraction System",
      desc: "Implemented an OCR pipeline using HuggingFace's nanonets/Nanonets-OCR-s model to extract structured invoice data. Includes memory-efficient image preprocessing, optimized inference workflows, and integration with downstream financial systems. Demonstrates practical model integration, memory optimization, and production inference engineering.",
      img: "/images/hero/herbalens.jpg",
      alt: "OCR Invoice Extraction - Structured data extraction system",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: [
        "HuggingFace",
        "Nanonets OCR",
        "Python",
        "Image Processing",
        "OpenCV",
      ],
      category: "AI/ML - Document Intelligence",
      members: ["Tharuneswar Doddi"],
      features: [
        "HuggingFace Nanonets OCR integration",
        "Memory-efficient image preprocessing",
        "Structured invoice data extraction",
        "Optimized inference workflows",
        "Integration with financial systems",
      ],
      achievements: [
        "📄 Accurate structured data extraction",
        "💾 Memory-optimized preprocessing",
        "⚙️ Production inference engineering",
        "🔗 Financial system integration",
      ],
      duration: "1 month",
      status: "Completed",
    },
    {
      title: "Financial RAG Agent",
      desc: "Built a Retrieval-Augmented Generation system to answer queries about company financial data. Integrated LangChain with MongoDB and Qdrant for document ingestion and vector indexing. Enabled semantic search across financial documents with multi-step query reasoning. Demonstrates end-to-end RAG architecture, embedding search, and AI-driven document intelligence.",
      img: "/images/hero/flowfit.jpg",
      alt: "Financial RAG Agent - Document intelligence system",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: ["LangChain", "MongoDB", "Qdrant", "Python", "Vector Search"],
      category: "AI/ML - RAG Systems",
      members: ["Tharuneswar Doddi"],
      features: [
        "LangChain RAG pipeline implementation",
        "MongoDB document storage",
        "Qdrant vector indexing",
        "Semantic search across documents",
        "Multi-step query reasoning",
        "Financial data intelligence",
      ],
      achievements: [
        "🧠 Advanced RAG architecture",
        "📚 Semantic document search",
        "💬 Multi-step reasoning capabilities",
        "💼 Financial data intelligence",
      ],
      duration: "2 months",
      status: "Completed",
    },
    {
      title: "Real-Time Chat & Event Streaming System",
      desc: "Developed a real-time messaging architecture using WebSockets, MongoDB change streams, and MQTT integration. Features event-driven backend design with streaming data pipelines and real-time API architecture. Demonstrates expertise in building scalable, low-latency communication systems for modern applications.",
      img: "/images/projects/project1/1.jpg",
      alt: "Real-Time Chat System - Event-driven architecture",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: ["WebSockets", "MongoDB", "MQTT", "Python", "FastAPI"],
      category: "Full Stack - Real-Time Systems",
      members: ["Tharuneswar Doddi"],
      features: [
        "WebSocket real-time communication",
        "MongoDB change streams for event streaming",
        "MQTT message brokering",
        "Event-driven backend design",
        "Real-time API architecture",
        "Persistent message storage",
      ],
      achievements: [
        "⚡ Sub-second latency messaging",
        "🔄 Change stream event propagation",
        "📡 MQTT scalable brokering",
        "🔗 Event-driven architecture",
      ],
      duration: "2 months",
      status: "In Progress",
    },
    {
      title: "LinkedIn Posting Automation with AI (n8n)",
      desc: "Developed an automated LinkedIn content posting system using n8n workflow automation with LLM integration for dynamic content generation, automated scheduling, and publishing. Successfully deployed n8n on AWS EC2 with secure HTTPS, firewall rules, Nginx reverse proxy, and SSL renewal automation. Demonstrates DevOps expertise and intelligent automation capabilities.",
      img: "/images/projects/project2/1.jpg",
      alt: "LinkedIn AI Automation - Workflow automation system",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: [
        "n8n",
        "LLM APIs",
        "AWS EC2",
        "Nginx",
        "Docker",
        "Let's Encrypt",
      ],
      category: "Automation & DevOps",
      members: ["Tharuneswar Doddi"],
      features: [
        "n8n workflow automation platform",
        "LLM integration for content generation",
        "Automated LinkedIn posting",
        "Scheduled content publishing",
        "AWS EC2 deployment",
        "Secure HTTPS configuration",
        "Nginx reverse proxy setup",
        "SSL certificate automation with Let's Encrypt",
      ],
      achievements: [
        "🚀 Production n8n deployment on AWS",
        "🤖 LLM-powered content generation",
        "🔐 Secure HTTPS with auto-renewal",
        "📱 LinkedIn API integration",
      ],
      duration: "1.5 months",
      status: "Completed",
    },
  ],
  // Tab 1: Backend & API Projects
  [
    {
      title: "FastAPI Production Backend",
      desc: "Production-grade FastAPI backend with RESTful APIs, input validation, error handling, and database integration. Optimized for high-concurrency and reliability.",
      img: "/images/projects/project1/2.png",
      alt: "FastAPI Production Backend",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: ["FastAPI", "Python", "PostgreSQL", "Pydantic"],
      category: "Backend Development",
      members: ["Tharuneswar Doddi"],
      features: [
        "RESTful API design",
        "Request validation with Pydantic",
        "Database integration",
        "Error handling",
      ],
      duration: "1.5 months",
      status: "Completed",
    },
  ],
  // Tab 2: Infrastructure & DevOps
  [
    {
      title: "Docker & Kubernetes Deployment",
      desc: "Container orchestration and microservices deployment using Docker and Kubernetes. Experience with containerizing Python applications, managing container registries, and orchestrating multi-service deployments in production environments.",
      img: "/images/projects/project2/2.png",
      alt: "Docker & Kubernetes Infrastructure",
      link: "https://github.com/Tharuneswar2",
      demoLink: "#",
      techStack: ["Docker", "Kubernetes", "Linux", "AWS"],
      category: "DevOps & Infrastructure",
      members: ["Tharuneswar Doddi"],
      features: [
        "Docker containerization",
        "Kubernetes orchestration",
        "Multi-service deployments",
        "Container registry management",
      ],
      duration: "1 month",
      status: "Completed",
    },
    {
      title: "AWS & Cloud Deployment",
      desc: "Cloud deployment experience with AWS EC2, secure domain configuration with DuckDNS, and production-grade server configuration. Experience with Linux server administration, firewall rules, and system optimization.",
      img: "/images/projects/project2/3.png",
      alt: "AWS Cloud Deployment",
      link: "#",
      demoLink: "#",
      techStack: ["AWS EC2", "Linux", "Nginx", "DuckDNS", "Let's Encrypt"],
      category: "Cloud & DevOps",
      members: ["Tharuneswar Doddi"],
      features: [
        "AWS EC2 instance management",
        "Linux server configuration",
        "Nginx reverse proxy setup",
        "HTTPS with Let's Encrypt",
      ],
      duration: "Ongoing",
      status: "In Progress",
    },
  ],
  // Tab 3: Technical Skills & Expertise
  [
    {
      title: "Transformer Architecture & LLMs",
      desc: "Deep expertise in transformer-based language model design, implementation, and optimization. Understanding of self-attention mechanisms, multi-head attention, positional encodings, and feed-forward networks.",
      img: "/images/projects/project1/3.png",
      alt: "Transformer Architecture Expertise",
      link: "#",
      demoLink: "#",
      techStack: ["PyTorch", "Transformers Library", "Python"],
      category: "AI/ML Expertise",
      members: ["Tharuneswar Doddi"],
      features: [
        "Transformer architecture understanding",
        "Model implementation from scratch",
        "Training optimization",
        "Fine-tuning techniques",
      ],
      duration: "Ongoing",
      status: "In Progress",
    },
    {
      title: "Vector Databases & Embeddings",
      desc: "Production experience with vector databases (Qdrant), embedding generation, similarity search, and semantic indexing. Understanding of vector distance metrics and scalable retrieval systems.",
      img: "/images/projects/project2/4.png",
      alt: "Vector Database Expertise",
      link: "#",
      demoLink: "#",
      techStack: ["Qdrant", "Embeddings", "Python", "Semantic Search"],
      category: "Database Expertise",
      members: ["Tharuneswar Doddi"],
      features: [
        "Qdrant vector indexing",
        "Embedding generation",
        "Similarity search implementation",
        "Semantic ranking",
      ],
      duration: "Ongoing",
      status: "In Progress",
    },
  ],
];
